# Generated by Django 5.0.7 on 2024-07-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jet',
            old_name='fractory_year',
            new_name='factory_year',
        ),
    ]
